### ISSUE TITLE
[Issue] Game Breaking Anvil Issue

### ISSUE THREAD

**Issue by qSeek** [GC-spigot/AdvancedEnchantments#2081]
## Details

**Describe the bug**

Basically you can't apply more than 1 vanilla enchantments on items after the AE 8.3.4 update.
**To Reproduce**

Get an item with any vanilla enchantment and try to apply one more enchantment using books in anvil.
**Screenshots / Video**

https://i.gyazo.com/ee9037ab1ff2eee39e3154521986b996.gif

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/qarazokexe
- Server log: https://mcpaste.io/258ce4dde0bd9acb

**Comment by Insprill** [comment]
I couldn't reproduce this on Paper or Spigot. If you disable anvil support does it work normally?

**Comment by Agaloth** [comment]
Happened to me on airplane purpur 1.16.5. (https://ci.tivy.ca/job/Airplane-Purpur-1.16/)

Fixed once I switched the anvil support off.

**Comment by Insprill** [comment]
Interesting, I made a few changes internally and fixed quite a few anvil issues for the next update so once that's out please get back to me as to if this issue is fixed.

**Comment by scottyboii** [comment]
Can reproduce:

Paper version git-Paper-601 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
AdvancedEnchantments 8.3.4

Disabling either the plugin or anvil support "fixes" the bug. 

Will make sure to check out on the next update.

**Comment by Insprill** [comment]
Can y'all see if 8.3.7 fixes this?

**Comment by J14P** [comment]
I am still getting the same error and I see that the pickaxe has experience 5 in the anvil but it won't let me take the pickaxe out of the anvil. The work around for this is giving myself 100% blackscrolls until I remove the lower level enchant and then applying the higher level enchant

**Comment by Insprill** [comment]
Can y'all see if this is still an issue on 8.4.0?

**Comment by J14P** [comment]
insprill i downloaded the lastest version and when i do /ae about it says i am running 8.3.9 when 8.4.0 is the lastest but as of 8.3.9 it still isn't working. I wonder if there is supposed to be an exp amount requirement that is not showing up in the anvil

**Comment by Insprill** [comment]
Looks like the internal version didn't get updated before release, as long as you downloaded 8.4.0 you should be running it. I'll see if i can reproduce tomorrow

**Comment by J14P** [comment]
As of 8.4.1 i am still unable to upgrade my experience 1 pickaxe to experience 5 using an experience 5 book. In the anvil it shows that the pickaxe will output with experience 5 but it doesn't let me take it from the anvil still.

**Comment by OrkeePlayz** [comment]
As of now (8.4.4), I can still reproduce the same issue.

**Comment by Insprill** [comment]
Do any of y'all have any more info on this? I tried exactly what qSeek did in the video and it worked just fine (paper-75, 1.17, Java 16.0.1)

**Comment by OrkeePlayz** [comment]
Well, do you let AE take control of the anvil. If not, then it would work with regular enchantment books. If it is set to true, then the issue is present.

**Comment by Insprill** [comment]
I think I've finally found the cause of this issue. The next issue should solve it but I will leave this open until it's confirmed.

**Comment by Insprill** [comment]
Now that 8.6.8 is out, can y'all confirm this issue is fixed?

**Comment by Insprill** [comment]
Going to assume it's fixed.
