### ISSUE TITLE
ADD_DURABILITY_ITEM was not worked after cast mythic skill.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3672]
### Describe the bug

재련:
  display: '%group-color%재련'
  type: ATTACK_MOB;MINING;SHOOT;SHOOT_MOB
  group: 커먼
  applies:
  - ALL_AXE
  - ALL_SWORD
  - NETHERITE_PICKAXE
  - DIAMOND_PICKAXE
  - IRON_PICKAXE
  - STONE_PICKAXE
  - WOOD_PICKAXE
  - ALL_SPADE
  - ALL_HOE
  - BOW
  - CROSSBOW
  levels:
    '1':
      chance: 20
      effects:
      - ADD_DURABILITY_ITEM:-1
    '2':
      chance: 25
      effects:
      - ADD_DURABILITY_ITEM:-2
    '3':
      effects:
      - ADD_DURABILITY_ITEM:-9

### How to reproduce

1. apply enchant that i described below:
재련:
  display: '%group-color%재련'
  type: ATTACK_MOB;MINING;SHOOT;SHOOT_MOB
  group: 커먼
  applies:
  - ALL_AXE
  - ALL_SWORD
  - NETHERITE_PICKAXE
  - DIAMOND_PICKAXE
  - IRON_PICKAXE
  - STONE_PICKAXE
  - WOOD_PICKAXE
  - ALL_SPADE
  - ALL_HOE
  - BOW
  - CROSSBOW
  levels:
    '1':
      chance: 20
      effects:
      - ADD_DURABILITY_ITEM:-1
    '2':
      chance: 25
      effects:
      - ADD_DURABILITY_ITEM:-2
    '3':
      effects:
      - ADD_DURABILITY_ITEM:-9

2. cast mythic skill several times (mythicitems)
3. attack monsterg

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/235dfb9e-3193-42cb-a9d4-a847c5df7ee9

### "/ae plinfo" link

https://paste.md-5.net/cutexanaje

**Comment by ThomasWega** [comment]
are you sure your mythic mobs entity doesnt have ignoreenchantments attribute?

**Comment by Ecilpse** [comment]
yes. that mob has ignoreshield, ignorearmor. not ignoreenchantments.
- basedamage{m=1;is=true;i=true}

**Comment by ThomasWega** [comment]
The durability was broken completely. I've fixed it. Let's wait for the next update and see if that fixes it. I will leave this open for now

**Comment by ThomasWega** [comment]
Can you please try now in 9.4.8?

**Comment by Ecilpse** [comment]
> Can you please try now in 9.4.8?

i think its fixed now.
I'll inform here if there's a problem.

**Comment by ThomasWega** [comment]
Thank you

**Comment by Ecilpse** [comment]
> Collaborator
some player said that the effect doesn't work sometimes. I think it's not fixed.

**Comment by Ecilpse** [comment]
> Thank you
> 
> 

I think something changed in add durability. It seemd effect was worked, but increase amount of add durability was different with old version.
I adjust amount of add durability, it seemd fixed. But i'll keep see it totally fixed

**Comment by ThomasWega** [comment]
It indeed was. It was incorrect and was fixed last version
