### ISSUE TITLE
Duplication glitch on REPEATING enchants that cost souls 

### ISSUE THREAD

**Issue by ValhallaCraft** [GC-spigot/AdvancedEnchantments#4596]
### Describe the bug

When a repeating type enchant has a soul cost it is easily duplicated when you right click equip from your hotbar and then scroll. 

### How to reproduce

Methods to replicate:
Have a REPEATING type enchant that costs souls like this one:
```
glowing:
  display: '{#FF9A8B}G{#FF928B}l{#FF8A8A}o{#FF828A}w{#FF7A89}i{#FF7289}n{#FF6A88}g'
  description: |-
   Gives permanent night vision. (Cost: 1 Soul/5 Seconds)
  applies-to: Helmet
  type: REPEATING
  group: UNIQUE
  applies:
  - ALL_HELMET
  levels:
    '1':
      time: 5
      souls: 1
      effects:
      - POTION:NIGHT_VISION:0:600
```

Have helmet in hot bar, right click to equip and then scroll. Player must be non-operator so the enchant is actively costing souls. 

### Screenshots / Videos

https://github.com/user-attachments/assets/8fba1404-8b77-4d12-ae3a-d0ff0d3a9cbb

### "/ae plinfo" link

https://paste.md-5.net/usadiyiyez

### Server Log

https://mclo.gs/Q3EeG2R

**Comment by ValhallaCraft** [comment]
Also just wanted to add i was able to reproduce this in a solitary environment on latest Purpur 1.21.1 with only AE on the server.

**Comment by ThomasWega** [comment]
Should be fixed in the next update

**Comment by ValhallaCraft** [comment]
> Should be fixed in the next update

Still occurs on latest update.

**Comment by GC-spigot** [comment]
Read the changelog :) the fix has not yet been released.

**Comment by AshleyFOXXX** [comment]
The issue still exists on mine.
But on my end, when neutralize enchantment is on the bow, and when you shoot yourself with it, the bow gets duplicated along with the same enchantments with it. And it is an infinite dup
