### ISSUE TITLE
Using custom head textures for AE Items not working

### ISSUE THREAD

**Issue by JorisvD01** [GC-spigot/AdvancedEnchantments#4981]
### Describe the bug

Hello,

I want to use custom heads (headdatabase, or just base64) as the materials for some of my items like the bloktrak, slot-increaser etc.

I've tried looking in the documentation how this should work, but tried everything I could find (also asked other users and support in the discord, but they didn't know a working way), and support mentioned to ask it here.

This is what I found in the docs; https://wiki.advancedplugins.net/configuration/config-items but that sadly didn't work.

Things I've tried;

```
type: 'player_head'
owner: '{base64}'
```

```
type: 'player_head'
head: '{base64}'
```

```
type: 'player_head'
texture: '{base64}'
```

```
type: 'hdb-{code}'
```

```
type 'basehead-{base64}'
```

### How to reproduce

Try to configure a custom head as the material for one of the AE items, using one of aboves mentioned config ways.

### "/ae plinfo" link

https://pastes.dev/CB2n1lRaMF

### Server Log

https://mclo.gs/Fc4sgh4

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Next update the owner value will work. Thanks for reporting

**Comment by JorisvD01** [comment]
> Next update the owner value will work. Thanks for reporting

Hello,
We've now updated and it is working on some of the heads, but not all for some reason. For example;

This one is working
```
  blocktrak:
    type: player_head
    owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjAxZTFlMGRiMjBjMGE5OTcxNjY1MzI2MjE1MmQ3ODZhMzUwYWVhZDE2NTAxYjc5YjhhNTliN2I1MzNlMzgxZiJ9fX0=
    id: 0
    custom-model-data: 0
    force-glow: true
    name: '&6&lBlokken Amulet'
    lore:
    - '&8Enchanting Upgrade'
    - ''
    - '&6&l♦ &7Voeg dit amulet toe aan een item'
    - '   &7om te kunnen zien hoeveel blokken'
    - '   &7je ermee hebt gehakt!'
    messages:
      success:
      - '&6&l[C&b&lV]&7&l・&5Enchanten &7| &7Je hebt succesvol het Blokken Amulet gebruikt!'
    settings:
      lore-display: '&7Blokken gebroken: &6%stats%'
```

But this one, using the same head data does not.
```
  stattrak:
    type: player_head
    owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjAxZTFlMGRiMjBjMGE5OTcxNjY1MzI2MjE1MmQ3ODZhMzUwYWVhZDE2NTAxYjc5YjhhNTliN2I1MzNlMzgxZiJ9fX0=
    id: 0
    custom-model-data: 0
    force-glow: true
    name: '&4&lPVP Amulet'
    lore:
    - '&8Enchanting Upgrade'
    - ''
    - '&4&l♦ &7Voeg dit amulet toe aan een item'
    - '   &7om te kunnen zien hoeveel spelers'
    - '   &7je ermee hebt vermoord!'
    messages:
      success:
      - '&6&l[C&b&lV]&7&l・&5Enchanten &7| &7Je hebt succesvol het PVP Amulet gebruikt!'
    settings:
      lore-display: '&7Spelers vermoord: &4%stats%'
```

**Comment by JorisvD01** [comment]
The only difference is the fact one is on bloktrak, and the other is on stattrak

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Apologies and thanks for the clarification <3

**Comment by JorisvD01** [comment]
Tried the latest version (9.21.11), but this issue is only fixed on the stattracker. Right now only the soultracker and holywhitescroll are not working, the others we are using are.

Our current config; https://pastebin.com/1s2v1aYv
I tried the texture from another head on one of the not-working ones, but still gives a steve head :(

**Comment by ThomasWega** [comment]
Changed it. I've set the path incorrectly for few. Thanks for letting me know. If you find any more just let me know

**Comment by JorisvD01** [comment]
> Changed it. I've set the path incorrectly for few. Thanks for letting me know. If you find any more just let me know

Is this updated in the newest jar already? In 9.22.0 this is still not fixed for the soultracker and holywhitescroll :/

**Comment by ThomasWega** [comment]
Has only been merged today. So next update

**Comment by leon37921** [comment]
hey, I can't use custom heads in menus, especially the alchemist. That might be related to this bug.
I tried the configurations above (with base64) and other variations, but it either shows nothing at all or just a normal steve-head.
AE 9.22.4, paper 1.20.4
